name: ci-practice-git

on:
    push:

jobs:
      build:
            runs-on:ubuntu-latest

      steps:
           - name: Checkout code
             uses: actions/checkout@v4

           - name: show files
             run: ls -la

           - name: Run basic text
             run: |
               test -f app.txt
               echo "CI test passed"
