name: Git Practice CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show files
        run: ls -la

      - name: Run basic test
        run: |
          test -f app.txt
          echo "CI test passed"
